-- StayFinder core schema (issue #2). See docs/database.md for the ER diagram.
-- Conventions: uuid primary keys, timestamptz stored in UTC, money as numeric(10,2),
-- enum-like columns as lowercase text with a CHECK so the values match the JSON API.

-- Lets the bookings exclusion constraint compare listing_id (uuid) inside a GiST index.
create extension if not exists btree_gist;

create table users (
    id            uuid         primary key default gen_random_uuid(),
    role          varchar(16)  not null check (role in ('customer', 'host', 'admin')),
    name          varchar(120) not null,
    email         varchar(254) not null unique check (email = lower(email)),
    password_hash varchar(100) not null,
    phone         varchar(32),
    created_at    timestamptz  not null default now(),
    updated_at    timestamptz  not null default now(),
    -- Hosts register with a contact phone (issue #6).
    constraint users_host_phone_required check (role <> 'host' or phone is not null)
);

create table listings (
    id              uuid          primary key default gen_random_uuid(),
    host_id         uuid          not null references users (id),
    title           varchar(120)  not null,
    description     text          not null,
    address_line1   varchar(200)  not null,
    city            varchar(100)  not null,
    state           varchar(2)    not null,
    zip             varchar(5)    not null check (zip ~ '^[0-9]{5}$'),
    -- Null until the address is geocoded.
    lat             double precision check (lat between -90 and 90),
    lng             double precision check (lng between -180 and 180),
    price_per_night numeric(10, 2) not null check (price_per_night > 0),
    max_guests      integer       not null check (max_guests >= 1),
    -- House hours, in the listing's own time zone.
    check_in_time   time          not null default '15:00',
    check_out_time  time          not null default '11:00',
    time_zone       varchar(64)   not null default 'America/Los_Angeles',
    contact_phone   varchar(32),
    contact_email   varchar(254),
    status          varchar(16)   not null default 'pending'
                                  check (status in ('pending', 'approved', 'removed')),
    -- Why an admin rejected or removed it, or why the host took it down.
    status_reason   text,
    submitted_at    timestamptz   not null default now(),
    reviewed_at     timestamptz,
    reviewed_by     uuid          references users (id),
    created_at      timestamptz   not null default now(),
    updated_at      timestamptz   not null default now()
);

create index listings_host_idx on listings (host_id);
create index listings_status_city_idx on listings (status, city);
create index listings_zip_idx on listings (zip);

create table listing_photos (
    id         uuid          primary key default gen_random_uuid(),
    listing_id uuid          not null references listings (id) on delete cascade,
    url        varchar(1024) not null,
    caption    varchar(200),
    -- 0 is the cover photo shown in search.
    position   integer       not null default 0 check (position >= 0),
    created_at timestamptz   not null default now()
);

create index listing_photos_listing_idx on listing_photos (listing_id, position);

-- Predefined list hosts pick from (issue #22); rows are inserted by V2.
create table amenities (
    id   integer     generated by default as identity primary key,
    name varchar(60) not null unique
);

create table listing_amenities (
    listing_id uuid    not null references listings (id) on delete cascade,
    amenity_id integer not null references amenities (id),
    primary key (listing_id, amenity_id)
);

create index listing_amenities_amenity_idx on listing_amenities (amenity_id);

-- Date ranges a listing can be booked (issue #21). Both ends are inclusive:
-- guests may check in on start_date and must check out by end_date.
create table availability (
    id         uuid        primary key default gen_random_uuid(),
    listing_id uuid        not null references listings (id) on delete cascade,
    start_date date        not null,
    end_date   date        not null,
    created_at timestamptz not null default now(),
    constraint availability_valid_range check (end_date > start_date)
);

create index availability_listing_idx on availability (listing_id, start_date);

create table bookings (
    id           uuid           primary key default gen_random_uuid(),
    listing_id   uuid           not null references listings (id),
    customer_id  uuid           not null references users (id),
    check_in     timestamptz    not null,
    check_out    timestamptz    not null,
    guests       integer        not null check (guests >= 1),
    total_cost   numeric(10, 2) not null check (total_cost >= 0),
    status       varchar(16)    not null default 'confirmed'
                                check (status in ('confirmed', 'cancelled')),
    cancelled_at timestamptz,
    created_at   timestamptz    not null default now(),
    constraint bookings_valid_range check (check_out > check_in),
    constraint bookings_cancelled_at check ((status = 'cancelled') = (cancelled_at is not null)),
    -- Last line of defence against double booking (issue #17): two confirmed
    -- stays on the same listing can never overlap. Surfaces as SQLSTATE 23P01.
    constraint bookings_no_overlap exclude using gist (
        listing_id with =,
        tstzrange(check_in, check_out, '[)') with &&
    ) where (status = 'confirmed')
);

create index bookings_customer_idx on bookings (customer_id, check_in);
create index bookings_created_idx on bookings (created_at);

create table reviews (
    id          uuid        primary key default gen_random_uuid(),
    listing_id  uuid        not null references listings (id),
    customer_id uuid        not null references users (id),
    -- One review per stay.
    booking_id  uuid        unique references bookings (id),
    rating      integer     not null check (rating between 1 and 5),
    comment     text,
    created_at  timestamptz not null default now()
);

create index reviews_listing_idx on reviews (listing_id, created_at);
